name: Run every Saturday morning

on:
  schedule:
    - cron: '0 4 * * 3' # 매주 토요일 오전 8시 (UTC) 실행

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.2.0' # 원하는 Node.js 버전 지정

      - name: Install dependencies
        run: npm install

      - name: Run script
        run: npm run build:start
